### ISSUE TITLE
Security Alerts; Severity: High

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/web-libraries#81]
---
due: 2022-04-03
--- 
    
**Describe the bug**
Please upgrade the following packages or dismiss the vulnerability as non-relevant:

`prismjs`
`node-fetch`
`immer`
`ansi-html`
`trim`

**To Reproduce**
1. Find vulnerability information https://github.com/Recidiviz/web-libraries/security/dependabot

**Comment by phenggeler** [comment]
@phenggeler - label applied: Due this month.

**Comment by macfarlandian** [comment]
Looked into this a bit -- these are all indirect dependencies via Storybook, which we do deploy into a static site. I'm pretty sure they will all be addressed by an upgrade to Storybook 6.5 which is still in alpha as of today. I think we can wait a bit to see if that comes out before the end of the month because I doubt there is much of a real threat from any of these packages; I don't think there is any real attack surface within the Storybook deployment itself since it doesn't communicate with any servers or anything? 

`node-fetch` is also a dependency of Semiotic, which could potentially cause some issues downstream, but there is not yet a Semiotic update that addresses it. (There is an impending major version bump so there could be some breaking changes associated with upgrading) Based on reading about the issue though I don't think it really affects us either (we don't fetch anything via Semiotic, and we don't run it in a Node environment).

**Comment by phenggeler** [comment]
@macfarlandian - sounds good. Let's touch base as we approach the due date and see if the Storybook upgrade has moved out of alpha

**Comment by phenggeler** [comment]
@macfarlandian - just touching base on this as we approach the end date. It looks like 2 more vulnerabilities have come in since we filed this ticket.

**Comment by macfarlandian** [comment]
Still no release from Storybook as of today. We can check in again at the beginning of next week

**Comment by phenggeler** [comment]
OK sounds good!

**Comment by phenggeler** [comment]
@phenggeler - label applied: Due this week.

**Comment by macfarlandian** [comment]
Still no update upstream; in the absence of this, I investigated a little more and can report that none of the packages listed in this ticket result in an actual vulnerability in our applications as they are not actually used except in build tooling. I'm going to dismiss them and close this issue.
